version: '3.0'

services:
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    command: tail -f /dev/null

  nsqd0:
    image: nsqio/nsq:v1.3.0
    command: >-
      nsqd
      --log-level debug
      --lookupd-tcp-address nsqlookupd0:4160
      --auth-http-address="nsq-auth:1325"
      --deflate=true

  nsqd1:
    image: nsqio/nsq:v1.3.0
    command: >-
      nsqd
      --log-level debug
      --lookupd-tcp-address nsqlookupd0:4160
      --deflate=true

  nsqlookupd0:
    image: nsqio/nsq:v1.3.0
    command: /nsqlookupd -log-level debug

  nsqadmin:
    image: nsqio/nsq:v1.3.0
    command:
      - nsqadmin
      - --http-address=0.0.0.0:4171
      - --lookupd-http-address=nsqlookupd0:4161
    depends_on:
      - nsqlookupd0
    ports:
      - "127.0.0.1:4171:4171"

  nsq-auth:
    image: zhimiao/nsq-auth:latest
    restart: always
    command: --secret="jV22WdmaXxHWAiAh"
